SHIPS_NAME = [
    "Star Destroyer",
    "Lambda-class Imperial shuttle",
    "Solar Sailer",
    "Death Star",
    "Invisible hand",
    "Tantive IV",
    "Imperial Landing Craft",
    "Rebel Blockade runner",
    "Naboo Royal Cruiser",
    "Nebulon-B Frigate",
    "Millennium Falcon",
    "Hammerhead Corvette",
    "Republic cruiser",
    "Trade Federation Battleship",
    "Naboo star skiff",
    "The Imperial Shuttle",
    "Jedi starfighters",
    "Slave I",
    "TIE Fighter",
    "Home One",
    "Sith Infiltrator",
    "Venator-class Star Destroyer",
    "Radiant VII",
    "Trade Federation landing ship",
    "X - wing",
    "Y - wing",
    ]

FIRST_NAME = [
    "Andrew",
    "Olivia",
    "Jason",
    "Dianne",
    "Kieran",
    "Joanna",
    "Tom",
    "Hoon",
    "Langley",
    "Chrisitian",
    "Joe",
    "Dustin",
    "Miranda",
    "Chen",
    "Mark",
    "Adam",
]

SECOND_NAME = [
    "Koji",
    "Cheng",
    "Tobin",
    "Doan",
    "Bew",
    "Vanderham",
    "Weston-Jones",
    "Lee",
    "Kirkwood",
    "McKay",
    "Taslim",
    "Nguyen",
    "Buckens",
    "Raison",
    "Tang",
    "Laas"
    "Dacascos",
    "Rayner",
]

RANK = [
    "Emperor",
    "Sith Lord",
    "Darth",
    "Grand Moff",
    "Moff",
    "Admiral",
    "General",
    "Commander",
    "Captain",
    "Lieutenant",
    "Ensign",
    "Sergeant",
    "Trooper",
]
