"""add speed field to Spaceship

Revision ID: 64a4439e01b0
Revises: a065c914227f
Create Date: 2023-11-20 14:10:22.449338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a4439e01b0'
down_revision: Union[str, None] = 'a065c914227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaceships', sa.Column('speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaceships', 'speed')
    # ### end Alembic commands ###
